from werkzeug.security import generate_password_hash
from app.models import db, User

def seed_users():

    demo = User(first_name="Demo", last_name="User", email="demouser@horizon.com", password="password", role="Mentee")
    db.session.add(demo)
    demo_mentor = User(first_name="Demo", last_name="Mentor", email="demomentor@horizon.com", password="password", role="Mentor")
    db.session.add(demo_mentor)
    # db.session.add(User(first_name="Duddette", last_name="Lebowski", email="lebowski@gmail.com", hashed_password=generate_password_hash("whiteRussian"), role="Mentor"))
    # db.session.add(User(first_name="Maria", last_name="Hill", email="hill@gmail.com", hashed_password=generate_password_hash("smulders"), role="Mentor"))
    # db.session.add(User(first_name="Monarch", last_name="Daisy", email="daisy@gmail.com", hashed_password=generate_password_hash("metamorphosis"), role="Mentor"))
    # db.session.add(User(first_name="Amy", last_name="George", email="george@gmail.com", hashed_password=generate_password_hash("whatsThe401"), role="Mentor"))
    # db.session.add(User(first_name="Matt", last_name="Foley", email="foley@gmail.com", hashed_password=generate_password_hash("vanDownByTheRiver"), role="Mentor"))
    # db.session.add(User(first_name="Arnold", last_name="Zola", email="zola@gmail.com", hashed_password=generate_password_hash("theAlgorithm"), role="Mentee"))
    # db.session.add(User(first_name="Adam", last_name="Mulchler", email="mulchler@gmail.com", hashed_password=generate_password_hash("freshPepper"), role="Mentee"))
    # db.session.add(User(first_name="Petler", last_name="Parkaler", email="parkaler@gmail.com", hashed_password=generate_password_hash("ohMyGod"), role="Mentee"))
    db.session.add(User(first_name="Amber", last_name="Yourrig", email="Yourrig@gmail.com", hashed_password=generate_password_hash("Yourrig1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/amber-mentee.jpg"))
    db.session.add(User(first_name="Angela", last_name="White", email="White@gmail.com", hashed_password=generate_password_hash("White1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/angela-mentee.jpg"))
    db.session.add(User(first_name="Danielle", last_name="Lodia", email="Lodia@gmail.com", hashed_password=generate_password_hash("Lodia1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/danielle-mentee.jpg"))
    db.session.add(User(first_name="Emily", last_name="Bursher", email="Bursher@gmail.com", hashed_password=generate_password_hash("Bursher1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/emily-mentee.jpg"))
    db.session.add(User(first_name="Gerald", last_name="Baumfinder", email="Baumfinder@gmail.com", hashed_password=generate_password_hash("Baumfinder1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/gerald-mentee.jpg"))
    db.session.add(User(first_name="Gina", last_name="Narem", email="Narem@gmail.com", hashed_password=generate_password_hash("Narem1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/gina-mentee.jpg"))
    db.session.add(User(first_name="James", last_name="Reginald", email="Reginald@gmail.com", hashed_password=generate_password_hash("Reginald1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/james-mentee.jpg"))
    db.session.add(User(first_name="Jorge", last_name="Alvares", email="Alvares@gmail.com", hashed_password=generate_password_hash("Alvares1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/jorge-mentee.jpg"))
    db.session.add(User(first_name="Karim", last_name="Irani", email="Irani@gmail.com", hashed_password=generate_password_hash("Irani1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/karim-mentee.jpg"))
    db.session.add(User(first_name="Mimi", last_name="Oetting", email="Oetting@gmail.com", hashed_password=generate_password_hash("Oetting1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/mimi-mentee.jpg"))
    db.session.add(User(first_name="Rehman", last_name="Paroush", email="Paroush@gmail.com", hashed_password=generate_password_hash("Paroush1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/rehman-mentee.jpg"))
    db.session.add(User(first_name="Shiyann", last_name="Reeseman", email="Reeseman@gmail.com", hashed_password=generate_password_hash("Reeseman1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/shiyann-mentee.jpg"))
    db.session.add(User(first_name="Sophia", last_name="Quiyov", email="Quiyov@gmail.com", hashed_password=generate_password_hash("Quiyov1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/sophia-mentee.jpg"))
    db.session.add(User(first_name="Tonsar", last_name="Dale", email="Dale@gmail.com", hashed_password=generate_password_hash("Dale1868!"), role="Mentee", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/tonsar-mentee.jpg"))
    db.session.add(User(first_name="Amanda", last_name="Darnelly", email="Darnelly@gmail.com", hashed_password=generate_password_hash("Darnelly1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/ananda-mentor.jpg"))
    db.session.add(User(first_name="Anita", last_name="Bonita", email="Bonita@gmail.com", hashed_password=generate_password_hash("Bonita1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/anita-mentor.jpg"))
    db.session.add(User(first_name="Dale", last_name="Lieberman", email="Lieberman@gmail.com", hashed_password=generate_password_hash("Lieberman1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/dale-mentor.jpg"))
    db.session.add(User(first_name="Dana", last_name="Drashum", email="Drashum@gmail.com", hashed_password=generate_password_hash("Drashum1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/dana-mentor.jpg"))
    db.session.add(User(first_name="Dani", last_name="Rothschild", email="Rothschild@gmail.com", hashed_password=generate_password_hash("Rothschild1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/dani-mentor.jpg"))
    db.session.add(User(first_name="Derek", last_name="Kochran", email="Kochran@gmail.com", hashed_password=generate_password_hash("Kochran1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/derek-mentor.jpg"))
    db.session.add(User(first_name="Eugenia", last_name="Stievoic", email="Stievoic@gmail.com", hashed_password=generate_password_hash("Stievoic1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/eugenia-mentor.jpg"))
    db.session.add(User(first_name="Eyomu", last_name="Corian", email="Corian@gmail.com", hashed_password=generate_password_hash("Corian1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/eyomu-mentor.jpg"))
    db.session.add(User(first_name="Franny", last_name="Mathers", email="Mathers@gmail.com", hashed_password=generate_password_hash("Mathers1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/franny-mentor.jpg"))
    db.session.add(User(first_name="Giselle", last_name="Shells", email="Shells@gmail.com", hashed_password=generate_password_hash("Shells1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/giselle-mentor.jpg"))
    db.session.add(User(first_name="Grayson", last_name="Dawes", email="Dawes@gmail.com", hashed_password=generate_password_hash("Dawes1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/grayson-mentor.jpg"))
    db.session.add(User(first_name="Greg", last_name="Paraborian", email="Paraborian@gmail.com", hashed_password=generate_password_hash("Paraborian1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/greg-mentor.jpg"))
    db.session.add(User(first_name="Hillary", last_name="Stuff", email="Stuff@gmail.com", hashed_password=generate_password_hash("Stuff1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/hillary-mentor.jpg"))
    db.session.add(User(first_name="Hussain", last_name="Dinka", email="Dinka@gmail.com", hashed_password=generate_password_hash("Dinka1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/hussain-mentor.jpg"))
    db.session.add(User(first_name="Janet", last_name="Armstrong", email="Armstrong@gmail.com", hashed_password=generate_password_hash("Armstrong1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/janet-mentor.jpg"))
    db.session.add(User(first_name="Jeremy", last_name="Weiner", email="Weiner@gmail.com", hashed_password=generate_password_hash("Weiner1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/jeremy-mentor.jpg"))
    db.session.add(User(first_name="Jerome", last_name="Jackson", email="Jackson@gmail.com", hashed_password=generate_password_hash("Jackson1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/jerome-mentor.jpg"))
    db.session.add(User(first_name="Jess", last_name="Tatiana", email="Tatiana@gmail.com", hashed_password=generate_password_hash("Tatiana1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/jess-mentor.jpg"))
    db.session.add(User(first_name="Jesse", last_name="Morales", email="Morales@gmail.com", hashed_password=generate_password_hash("Morales1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/jesse-mentor.jpg"))
    db.session.add(User(first_name="Jessica", last_name="Hera", email="Hera@gmail.com", hashed_password=generate_password_hash("Hera1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/jessica-mentor.jpg"))
    db.session.add(User(first_name="Joshua", last_name="Barter", email="Barter@gmail.com", hashed_password=generate_password_hash("Barter1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/joshua-mentor.jpg"))
    db.session.add(User(first_name="Mike", last_name="Rolachek", email="Rolachek@gmail.com", hashed_password=generate_password_hash("Rolachek1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/mike-mentor.jpg"))
    db.session.add(User(first_name="Nadu", last_name="Mayori", email="Mayori@gmail.com", hashed_password=generate_password_hash("Mayori1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/nadu-mentor.jpg"))
    db.session.add(User(first_name="Nancy", last_name="Belmont", email="Belmont@gmail.com", hashed_password=generate_password_hash("Belmont1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/nancy-mentor.jpg"))
    db.session.add(User(first_name="Olivia", last_name="Stratschu", email="Stratschu@gmail.com", hashed_password=generate_password_hash("Stratschu1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/olivia-mentor.jpg"))
    db.session.add(User(first_name="Pam", last_name="Wasply", email="Wasply@gmail.com", hashed_password=generate_password_hash("Wasply1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/pam-mentor.jpg"))
    db.session.add(User(first_name="Raya", last_name="Goinner", email="Goinner@gmail.com", hashed_password=generate_password_hash("Goinner1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/raya-mentor.jpg"))
    db.session.add(User(first_name="Roger", last_name="Leerstein", email="Leerstein@gmail.com", hashed_password=generate_password_hash("Leerstein1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/roger-mentor.jpg"))
    db.session.add(User(first_name="Ronda", last_name="Moskowitz", email="Moskowitz@gmail.com", hashed_password=generate_password_hash("Moskowitz1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/ronda-mentor.jpg"))
    db.session.add(User(first_name="Syed", last_name="Hamrani", email="Hamrani@gmail.com", hashed_password=generate_password_hash("Hamrani1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/syed-mentor.jpg"))
    db.session.add(User(first_name="Valerie", last_name="Wong", email="Wong@gmail.com", hashed_password=generate_password_hash("Wong1868!"), role="Mentor", profile_photo="https://horizons-aa.s3.us-east-2.amazonaws.com/headshots/valerie-mentor.jpg"))
    db.session.commit()

# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_users():
    db.session.execute('TRUNCATE users RESTART IDENTITY CASCADE;')
    db.session.commit()
