"""empty message

Revision ID: 6b30e553d670
Revises: 273b2bfcb3f2
Create Date: 2021-05-20 21:48:22.466984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b30e553d670'
down_revision = '273b2bfcb3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_url')
    # ### end Alembic commands ###
